[package]
name = "rdk"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bindgen = "0.69.4"
rand = "0.8.5"
rusty_jsc = "0.1.0"
rusty_jsc_macros = "0.1.0"
wasm3 = "0.3.1"
wasm3-sys = "0.3.0"
