[package]
name = "smoljs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
base64 = "0.21.7"
rusty_jsc = "0.1.0"
rusty_jsc_macros = "*"
